[app]
address = ":9000"

# The website URL to be used on the frontend pages.
# Example: portal.site.com
root_url = "http://localhost:9000"

manifest_uri = "/funding.json"
wellknown_uri = "/.well-known/funding-json-urls"

[data_files]
spdx = "data/spdx.json"
languages = "data/languages.json"
currencies = "data/currencies.json"

[site]
enable_captcha = false
captcha_key = ""
captcha_secret = ""


[crawl]
# Number of concurrent goroutine workers crawling manifests.
workers = 100

# The frequency at which an individual manifest should be re-crawled and re-scanned.
# This is based on the "updated_at" field of a manifest record.
manifest_age = "5 DAYS"

# Number of records to fetch from the DB in one shot and queue for crawling.
batch_size = 10000

# If a host returns 429, disable requests to it for the rest of the session.
skip_ratelimited_host = true

# HTTP requests.
max_host_conns = 100
attempts = 3 # minimum one
req_timeout = "3s"
max_bytes = 320000 # bytes
useragent = "floss-fund-crawler"

[db]
host = "localhost"
port = 5432
db = "floss"
user = "floss"
password = "floss"
